//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDetailsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Employee
    {
        public int Emp_ID { get; set; }
        public string Emp_Code { get; set; }
        public string Emp_Name { get; set; }
        public string Address { get; set; }
        public string Email_ID { get; set; }
        public string Phone_No { get; set; }
        public string Designation { get; set; }
    }
}
